import type { MetadataRoute } from 'next';
import { SITE_NAME, SITE_DESCRIPTION } from '@/lib/constants';

/**
 * Web app manifest enables iOS "Add to Home Screen" with a polished
 * standalone shell, plus unlocks Web Push notifications on iOS 16.4+
 * (which only deliver to PWAs that have been installed). The icons
 * here are dynamically generated by `app/icon.tsx` and
 * `app/apple-icon.tsx` — Next.js automatically wires both into the
 * manifest's `icons` array based on the file conventions, so we do
 * not need to repeat them here.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE_NAME,
    short_name: SITE_NAME,
    description: SITE_DESCRIPTION,
    start_url: '/',
    display: 'standalone',
    background_color: '#0f172a',
    theme_color: '#a855f7',
    orientation: 'portrait',
    categories: ['social', 'lifestyle', 'travel', 'events'],
  };
}
